os: linux
sudo: required
language:
  - minimal
services:
  - docker

compiler:
  -gcc

before_install:
  - pip install --user cpp-coveralls

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi
  - mkdir build
  - cd build
  - cmake ..
  - make

jobs:
  include:
    - name: "tests"
      script:
        - ctest -V
    - name: "checks"
      script:
        - chmod 755 scripts/*.sh
        - docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/checks.sh  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
